### ISSUE TITLE
Mongo DB

### ISSUE THREAD

**Issue by yeomann** [Codebrahma/Restaurant-Express-API#6]
Hi, thank you for sharing Backend. can you please share your Mongo DB file? i am new to Mongo that's why wondering how API will look like for now.

**Comment by prasanna1211** [comment]
@yeomann Please find the DB dump https://ufile.io/npyms.

**Comment by yeomann** [comment]
thank you for the DUMP @prasanna1211

**Comment by boogbig** [comment]
Hi @prasanna1211, Thank you for sharing. May I request for DB dump again?
The link you gave on 26 Nov are not working now, https://ufile.io/npyms
